"""created a column in pitchs and a virtual column in users

Revision ID: 4bcdb3939057
Revises: acc32ba91d81
Create Date: 2018-09-09 08:49:08.215167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcdb3939057'
down_revision = 'acc32ba91d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitchs', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitchs', 'users', ['author'], ['id'])
    op.drop_constraint('users_pitch_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitch_fkey', 'users', 'pitchs', ['pitch'], ['id'])
    op.drop_constraint(None, 'pitchs', type_='foreignkey')
    op.drop_column('pitchs', 'author')
    # ### end Alembic commands ###
